before:
    hooks:
        - go mod download
builds:
  - env:
        - CGO_ENABLED=0
    goos:
        - linux
        - windows
        - darwin
archives:
    - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    - format: binary
checksum:
    name_template: 'checksums.txt'
snapshot:
    name_template: "{{ .Tag }}-next"
changelog:
    skip: true
