name: Test

on:
    pull_request:
    push:

jobs:
    test:
        name: Test
        runs-on: ubuntu-22.04
        steps:
            -
                name: Checkout
                uses: actions/checkout@v3
            -
                name: Set up Go
                uses: actions/setup-go@v3
                with:
                    go-version: 1.22
            -
                name: Run tests
                run: go test ./...
